using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Text;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class IFFConsoleWindow : FancyWindow,
    IComputerWindow<IFFConsoleBoundUserInterfaceState>
{
    private const int SignatureHexLength = 6;
    private readonly ButtonGroup _showIFFButtonGroup = new();
    private readonly ButtonGroup _showVesselButtonGroup = new();
    private readonly StyleBoxFlat _swatchStyleBox = new();
    private bool _canEditColor;
    private bool _canEditDesignation;
    private bool _designationOptionsLoaded;
    private bool _suppressDesignationEvent;
    public event Action<bool>? ShowIFF;
    public event Action<bool>? ShowVessel;
    public event Action<string>? SetColor;
    public event Action<IFFDesignation>? SetDesignation;

    public IFFConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        ShowIFFOffButton.Group = _showIFFButtonGroup;
        ShowIFFOnButton.Group = _showIFFButtonGroup;
        ShowIFFOnButton.OnPressed += args => ShowIFFPressed(true);
        ShowIFFOffButton.OnPressed += args => ShowIFFPressed(false);

        ShowVesselOffButton.Group = _showVesselButtonGroup;
        ShowVesselOnButton.Group = _showVesselButtonGroup;
        ShowVesselOnButton.OnPressed += args => ShowVesselPressed(true);
        ShowVesselOffButton.OnPressed += args => ShowVesselPressed(false);

        SignatureColorSwatch.PanelOverride = _swatchStyleBox;
        DesignationOptionButton.OnItemSelected += args => OnDesignationSelected(args.Id);

        ApplyColorButton.OnPressed += _ => ApplySignatureColor();
        SignatureColorLineEdit.OnTextEntered += args => ApplySignatureColor(args.Text);
        SignatureColorLineEdit.OnTextChanged += args => OnColorTextChanged(args.Text);
    }

    private void ShowIFFPressed(bool pressed)
    {
        ShowIFF?.Invoke(pressed);
    }

    private void ShowVesselPressed(bool pressed)
    {
        ShowVessel?.Invoke(pressed);
    }

    private void ApplySignatureColor(string? text = null)
    {
        var value = SanitizeColorHex(text ?? SignatureColorLineEdit.Text);

        if (value.Length != SignatureHexLength)
            return;

        SetColor?.Invoke($"#{value}");
    }

    private void EnsureDesignationOptions()
    {
        if (_designationOptionsLoaded)
            return;

        DesignationOptionButton.Clear();
        DesignationOptionButton.AddItem(Loc.GetString("iff-console-designation-ship"), (int)IFFDesignation.Ship);
        DesignationOptionButton.AddItem(Loc.GetString("iff-console-designation-station"), (int)IFFDesignation.Station);
        _designationOptionsLoaded = true;
    }

    private void OnDesignationSelected(int id)
    {
        if (_suppressDesignationEvent)
            return;

        if (!_canEditDesignation)
            return;

        if (id < byte.MinValue || id > byte.MaxValue)
            return;

        var designationId = (byte)id;
        if (!Enum.IsDefined(typeof(IFFDesignation), designationId))
            return;

        DesignationOptionButton.SelectId(id);
        SetDesignation?.Invoke((IFFDesignation)designationId);
    }

    private void OnColorTextChanged(string text)
    {
        var sanitized = SanitizeColorHex(text);

        if (SignatureColorLineEdit.Text != sanitized)
        {
            SignatureColorLineEdit.Text = sanitized;
            SignatureColorLineEdit.CursorPosition = sanitized.Length;
        }

        UpdateApplyButtonState();
    }

    private static string SanitizeColorHex(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return string.Empty;

        var result = new StringBuilder(SignatureHexLength);

        foreach (var ch in value)
        {
            if (result.Length >= SignatureHexLength)
                break;

            if (Uri.IsHexDigit(ch))
                result.Append(char.ToUpperInvariant(ch));
        }

        return result.ToString();
    }

    private void UpdateApplyButtonState()
    {
        ApplyColorButton.Disabled = !_canEditColor || SignatureColorLineEdit.Text.Length != SignatureHexLength;
    }

    public void UpdateState(IFFConsoleBoundUserInterfaceState state)
    {
        if ((state.AllowedFlags & IFFFlags.HideLabel) != 0x0 || (state.AllowedFlags & IFFFlags.Hide) != 0x0)
        {
            ShowIFFOffButton.Disabled = false;
            ShowIFFOnButton.Disabled = false;

            if ((state.Flags & IFFFlags.HideLabel) != 0x0 || (state.Flags & IFFFlags.Hide) != 0x0)
            {
                ShowIFFOffButton.Pressed = true;
            }
            else
            {
                ShowIFFOnButton.Pressed = true;
            }
        }
        else
        {
            ShowIFFOffButton.Disabled = true;
            ShowIFFOnButton.Disabled = true;
        }

        if ((state.AllowedFlags & IFFFlags.Hide) != 0x0)
        {
            ShowVesselOffButton.Disabled = false;
            ShowVesselOnButton.Disabled = false;

            if ((state.Flags & IFFFlags.Hide) != 0x0)
            {
                ShowVesselOffButton.Pressed = true;
            }
            else
            {
                ShowVesselOnButton.Pressed = true;
            }
        }
        else
        {
            ShowVesselOffButton.Disabled = true;
            ShowVesselOnButton.Disabled = true;
        }

        _canEditColor = state.ColorEditable;
        UpdateApplyButtonState();
        SignatureColorLineEdit.Editable = state.ColorEditable;

        _canEditDesignation = state.DesignationEditable;
        EnsureDesignationOptions();
        DesignationOptionButton.Disabled = !_canEditDesignation;
        _suppressDesignationEvent = true;
        DesignationOptionButton.SelectId((int)state.Designation);
        _suppressDesignationEvent = false;

        var colorHex = state.SignatureColor.ToHexNoAlpha().TrimStart('#');
        SignatureColorLineEdit.Text = colorHex;
        _swatchStyleBox.BackgroundColor = state.SignatureColor;
        UpdateApplyButtonState();
    }
}
