using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CrewAssignments.AdminUI;

[GenerateTypedNameReferences]
public sealed partial class CodexWindow : DefaultWindow
{

    public CodexEui Owner;


    public CodexWindow(CodexEui owner)
    {
        Owner = owner;
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        var loc = IoCManager.Resolve<ILocalizationManager>();
    }
}
