using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Access.Components;
using Content.Shared.CCVar;
using Content.Shared.Security.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Security.Ui;

[GenerateTypedNameReferences]
public sealed partial class GenpopLockerMenu : FancyWindow
{
    [Dependency] private readonly IConfigurationManager _cfgManager = default!;

    public event Action<string, int, string>? OnConfigurationComplete;

    public GenpopLockerMenu(EntityUid owner, IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);


        Title = entMan.GetComponent<MetaDataComponent>(owner).EntityName;

        NameLabel.SetMarkup(Loc.GetString("genpop-locker-ui-label-name"));
        SentenceLabel.SetMarkup(Loc.GetString("genpop-locker-ui-label-sentence"));
        CrimeLabel.SetMarkup(Loc.GetString("genpop-locker-ui-label-crime"));

        SentenceEdit.Text = "1";
        CrimeEdit.Text = Loc.GetString("genpop-prisoner-id-crime-default");

        var maxIdJobLength = _cfgManager.GetCVar(CCVars.MaxIdJobLength);
        NameEdit.IsValid = val => !string.IsNullOrWhiteSpace(val) && val.Length <= maxIdJobLength;
        SentenceEdit.IsValid = val => TryParseSentenceDays(val, out _);
        CrimeEdit.IsValid = val => !string.IsNullOrWhiteSpace(val) && val.Length <= GenpopLockerComponent.MaxCrimeLength;

        NameEdit.OnTextChanged += _ => OnTextEdit();
        SentenceEdit.OnTextChanged += _ => OnTextEdit();
        CrimeEdit.OnTextChanged += _ => OnTextEdit();

        DoneButton.OnPressed += _ =>
        {
            if (TryParseSentenceDays(SentenceEdit.Text, out var sentenceDays))
                OnConfigurationComplete?.Invoke(NameEdit.Text, sentenceDays, CrimeEdit.Text);
        };
    }

    private void OnTextEdit()
    {
        DoneButton.Disabled = string.IsNullOrWhiteSpace(NameEdit.Text) ||
                              !TryParseSentenceDays(SentenceEdit.Text, out _) ||
                              string.IsNullOrWhiteSpace(CrimeEdit.Text);
    }

    private static bool TryParseSentenceDays(string value, out int days)
    {
        return GenpopLockerComponent.TryParseSentenceDays(value, out days, out _);
    }
}
