using Content.Shared.Access.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using static Content.Shared.Access.Components.IdPrinterConsoleComponent;

namespace Content.Client.Access.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class IdPrinterConsoleWindow : DefaultWindow
    {

        private readonly IdPrinterConsoleBoundUserInterface _owner;

        public IdPrinterConsoleWindow(IdPrinterConsoleBoundUserInterface owner, IPrototypeManager prototypeManager)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _owner = owner;

            PrintButton.OnPressed += _ => Print();
        }

        public void UpdateState(IdPrinterConsoleBoundUserInterfaceState state)
        {

        }

        public void Print()
        {
            _owner.Print();
            Close();
        }

    }
}
