using Content.Shared.MedicalRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Access.Systems;
using Robust.Shared.Utility;
using Content.Client.Message;

namespace Content.Client.MedicalRecords.UI;

[GenerateTypedNameReferences]
public sealed partial class MedicalRecordsConsoleWindow : DefaultWindow
{
    private readonly IPlayerManager _player;
    private readonly AccessReaderSystem _accessReader;
    public readonly EntityUid Console;

    public Action<string?>? OnPatientSelected;
    public Action<string>? OnRecordSaved;
    public Action<string>? OnFilterChanged;

    private bool _isPopulating;
    private Dictionary<string, string> _currentListing = new();

    public MedicalRecordsConsoleWindow(EntityUid console, IPlayerManager player, AccessReaderSystem accessReader)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Console = console;
        _player = player;
        _accessReader = accessReader;

        RecordTabs.SetTabTitle(0, "View Patient File");
        RecordTabs.SetTabTitle(1, "Edit Patient File");

        PatientListing.OnItemSelected += args =>
        {
            if (_isPopulating || PatientListing[args.ItemIndex].Metadata is not string patientName)
                return;

            OnPatientSelected?.Invoke(patientName);
        };

        PatientListing.OnItemDeselected += _ =>
        {
            if (!_isPopulating)
                OnPatientSelected?.Invoke(null);
        };

        PatientFilterValue.OnTextChanged += args =>
        {
            OnFilterChanged?.Invoke(args.Text);
        };

        SaveRecordButton.OnPressed += _ =>
        {
            OnRecordSaved?.Invoke(Rope.Collapse(MedicalRecordEdit.TextRope));
        };
    }

    public void UpdateState(MedicalRecordsConsoleState state, string filterText)
    {
        _isPopulating = true;

        PatientListing.Clear();
        PatientListing.ClearSelected();

        _currentListing = state.PatientListing ?? new();

        foreach (var (name, job) in _currentListing)
        {
            if (!string.IsNullOrEmpty(filterText) && !name.ToLower().Contains(filterText.ToLower()))
                continue;

            var item = PatientListing.AddItem($"{name} ({job})");
            item.Metadata = name;
            item.Selected = name == state.SelectedPatient;
        }

        PatientListing.SortItemsByText();
        _isPopulating = false;

        var selected = state.SelectedPatient != null;
        PatientDetailPanel.Visible = selected;
        SelectPatientStatus.Visible = !selected;

        if (selected && state.SelectedPatient != null)
        {
            PatientNameLabel.Text = state.SelectedPatient;
            PatientJobLabel.Text = state.PatientJob ?? "*Unassigned*";

            MedicalRecordLabel.SetMarkup(state.MedicalRecord ?? "");
            MedicalRecordEdit.TextRope = new Rope.Leaf(state.MedicalRecord ?? "");

            // Access control for editing
            var hasAccess = _player.LocalSession?.AttachedEntity is { } player
                && (_accessReader.IsAllowed(player, Console) || IsDoctor(player));

            RecordTabs.SetTabVisible(1, hasAccess);
            if (!hasAccess && RecordTabs.CurrentTab == 1)
            {
                RecordTabs.CurrentTab = 0;
            }
        }
    }

    private bool IsDoctor(EntityUid player)
    {
        var tags = _accessReader.FindAccessTags(player);
        return tags.Contains("Medical") || tags.Contains("ChiefMedicalOfficer") || tags.Contains("Command");
    }
}
