- type: job
  id: ExecutiveOfficer
  name: job-name-executive-officer
  description: job-description-executive-officer
  playTimeTracker: JobExecutiveOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Science
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 4h
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconExecutiveOfficer"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - AllAccess
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]
    - !type:AddComponentSpecial
      components:
        - type: CommandStaff

- type: startingGear
  id: ExecutiveOfficerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesCommand
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
      - Flash
      # - StationCharter

- type: chameleonOutfit
  id: ExecutiveOfficerChameleonOutfit
  job: ExecutiveOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatCapcap
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskGasCaptain
    neck: ClothingNeckCloakCap
