using Content.Client.Actions;
using Content.Client.Cargo.UI;
using Content.Client.Message;
using Content.Client.Store.Ui;
using Content.Shared.CrewAssignments;
using Content.Shared.CrewAssignments.Components;
using Content.Shared.CrewAssignments.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Linq;
using System.Security.AccessControl;
using System.Text;
using static Robust.Client.UserInterface.Controls.BaseButton;
using static Robust.Client.UserInterface.Controls.MenuBar;

namespace Content.Client.CrewAssignments.UI;

[GenerateTypedNameReferences]
public sealed partial class JobNetMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    public TimeSpan UntilNextPay = TimeSpan.Zero;
    public TimeSpan UntilNextPrec = TimeSpan.Zero;

    public JobNetBoundUserInterface? Owner;

    public JobNetMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MasterTabContainer.SetTabTitle(0, "Job Network");
        MasterTabContainer.SetTabTitle(1, "History");
        MasterTabContainer.SetTabTitle(2, "Sector");
        MasterTabContainer.SetTabTitle(3, "Upgrades");
        MasterTabContainer.SetTabTitle(4, "Precursor");
    }

    public void UpdateState(JobNetUpdateState state)
    {
        if (state.SpendAuth)
        {
            SLDetails.Visible = true;
            SpendingLabel.Text = $"${state.Spent}/${state.Spendable}";
        }
        else
        {
            SLDetails.Visible = false;
        }
        AccountBalanceLabel.Text = $"${state.Balance}";
        var dependencies = IoCManager.Instance!;
        var localPlayer = dependencies.Resolve<IPlayerManager>().LocalEntity;
        PossibleJobs.Clear();
        PossibleJobs.AddItem("Off Duty", 0);
        if (state.Stations != null)
        {
            int ind = 1;
            foreach (var kv in state.Stations)
            {

                PossibleJobs.AddItem(kv.Value, kv.Key);
                if (kv.Key == state.SelectedStation)
                    PossibleJobs.Select(ind);
                ind++;
            }
        }
        if (state.AssignmentName != null)
        {
            CSLabel.Text = state.AssignmentName;
            AssignmentDetails.Visible = true;
        }
        else
        {
            CSLabel.Text = "Off Duty";
            AssignmentDetails.Visible = false;
        }
        if (state.Wage != null)
        {
            WageLabel.Text = "$" + state.Wage.ToString();
        }
        else
        {
            WageLabel.Text = "$0";
        }
        if (state.RemainingMinutes != null)
        {
            UntilNextPay = state.RemainingMinutes.Value;
            TimeLabel.Text = UntilNextPay.ToString("mm\\:ss");
        }
        else
        {
            TimeLabel.Text = "Invalid";
        }
        CurrentObjectives.RemoveAllChildren();
        foreach (var objective in state.CurrentObjectives)
        {
            if (!objective.Visible) continue;
            WorldObjectiveEntryFragment entry = new(objective.Title, objective.Description, objective.Reward, null, null);
            CurrentObjectives.AddChild(entry);
        }
        CompletedObjectives.RemoveAllChildren();
        foreach (var objective in state.CompletedObjectives)
        {
            if (!objective.Visible) continue;
            WorldObjectiveEntryFragment entry = new(objective.Title, objective.Description, objective.Reward, objective.CompletedTime, objective.CompletedDescription);
            CompletedObjectives.AddChild(entry);
        }

        CodexContainer.RemoveAllChildren();

        var charName = "";
        if (localPlayer != null)
            charName = _entityManager.GetComponent<MetaDataComponent>(localPlayer.Value).EntityName;
        int totalNum = 0;
        int lockedNum = 0;
        foreach (var codexEntry in state.CodexEntries)
        {
            totalNum++;
            Button button = new();
            if (!codexEntry.Visible && !codexEntry.Whitelist.Contains(charName))
            {
                lockedNum++;
                button.Disabled = true;
            }
            button.Text = codexEntry.Title;
            button.OnPressed += _ => OnSelectCodex(codexEntry.Title, codexEntry.Description);
            CodexContainer.AddChild(button);
        }
        UnlockedNumberLabel.Text = $"[head=3][color=yellow]{totalNum - lockedNum}/{totalNum}[/color] Codex Entries Unlocked[/head]";
        _prototypeManager.Resolve(state.Level, out var levelProto);
        if (levelProto != null)
        {
            NetworkLevelPrototype? nextLevelProto = null;

            if (levelProto.Next != null)
                _prototypeManager.Resolve(levelProto.Next, out nextLevelProto);

            CurrentLevelLabel.Text = levelProto.Name;
            string levelDesc = $"Owned Tile Limit:[color=yellow]{levelProto.TileLimit}[/color]";
            CurrentBenefitsLabel.SetMarkup(levelDesc);
            string nextLevelDesc;
            if (nextLevelProto == null)
            {
                NextLevelLabel.Text = "Max Level Attained";
                nextLevelDesc = "[color=green]Maximum Level Attained[/color]";
                LevelPurchaseButton.Visible = false;
            }
            else
            {
                NextLevelLabel.Text = nextLevelProto.Name;
                nextLevelDesc = $"Owned Tile Limit:[color=green]{nextLevelProto.TileLimit}[/color]";
                LevelPurchaseButton.Visible = true;
                LevelPurchaseButton.Text = $"${nextLevelProto.Cost}";
            }
            NextBenefitsLabel.SetMarkup(nextLevelDesc);
        }

        PrecursorBalanceLabel.Text = state.Precursor.ToString();

        foreach (var objective in state.Objectives)
        {
            _prototypeManager.Resolve(objective, out var proto);
            if (proto == null) continue;
            PrecursorObjective precursorObjective = new();
            precursorObjective.ObjectiveLabel.Text = proto.Name;
            precursorObjective.RewardLabel.Text = $"Reward: {proto.Reward} Precursor";
            precursorObjective.SectorChaosLabel.Text = $"Will cause minor sector chaos.";
            PrecursorObjectives.AddChild(precursorObjective);

        }
        UntilNextPrec = state.PrecursorResetTime;
        ObjectiveTimerLabel.Text = UntilNextPrec.ToString("mm\\:ss");

        _prototypeManager.Resolve(state.RogueLevel, out var rogueLevel);
        if (rogueLevel != null)
        {
            PLevelText.Text = rogueLevel.Name;
            _prototypeManager.Resolve(rogueLevel.Next, out var nextLevel);
            if (nextLevel != null)
            {
                PLevelBar.MaxValue = nextLevel.Cost;
                PLevelBarText.Text = $"{state.XP} / {nextLevel.Cost}";
                PLevelBar.MinValue = rogueLevel.Cost;
                PLevelBar.Value = state.XP;
            }
            else
            {
                PLevelBar.MaxValue = 0;
                PLevelBarText.Text = $"Maximum Level Attained";
                PLevelBar.MinValue = rogueLevel.Cost;
                PLevelBar.Value = state.XP;
            }
            if (rogueLevel.ID == "RogueLevel1")
            {
                NetworkContentBox.Visible = false;
                NetworkRequirementLabel.Visible = true;
            }
            else
            {
                NetworkContentBox.Visible = true;
                NetworkRequirementLabel.Visible = false;
            }
            if (state.NetworkType == RogueNetworkType.None)
            {
                NetworkObjectivesRequirement.Visible = true;
                RogueNetworkObjectivesBox.Visible = false;
                PurchaseRequirements.Visible = true;
                PurchasesContent.Visible = false;
                DealerSelect.Visible = true;
                BountyHSelect.Visible = true;
                AssassinSelect.Visible = true;
            }
            else
            {
                NetworkObjectivesRequirement.Visible = false;
                RogueNetworkObjectivesBox.Visible = true;
                PurchaseRequirements.Visible = false;
                PurchasesContent.Visible = true;
                DealerSelect.Visible = false;
                BountyHSelect.Visible = false;
                AssassinSelect.Visible = false;

            }
            switch (state.NetworkType)
            {
                case RogueNetworkType.None:
                    RogueNetworkLabel.Text = "None";
                    break;
                case RogueNetworkType.BountyHunter:
                    RogueNetworkLabel.Text = "Bounty Hunter";
                    break;
                case RogueNetworkType.Assassin:
                    RogueNetworkLabel.Text = "Assassin";
                    break;
                case RogueNetworkType.Dealer:
                    RogueNetworkLabel.Text = "Dealer";
                    break;

            }
        }

    }

    private void OnSelectCodex(string title, string description)
    {
        if (Owner == null || Owner.CodexMenu == null) return;
        Owner.CodexMenu.UpdateState(title, description);
        Owner.CodexMenu.OpenCentered();

    }
    private void UpdateSkipButton(float deltaSeconds)
    {
        UntilNextPay -= TimeSpan.FromSeconds(deltaSeconds);
        if (UntilNextPay > TimeSpan.Zero)
        {
            TimeLabel.Text = UntilNextPay.ToString("mm\\:ss");
        }
        if (UntilNextPrec.TotalSeconds > 0)
        {
            UntilNextPrec -= TimeSpan.FromSeconds(deltaSeconds);
            ObjectiveTimerLabel.Text = UntilNextPrec.ToString("mm\\:ss");
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateSkipButton(args.DeltaSeconds);
    }

}
public sealed class JobButton : Button
{
    public int Id;
}
