- type: job
  id: Civilian
  name: job-name-civilian
  description: job-description-civilian
  playTimeTracker: JobCivilian
  startingGear: PassengerGear
  icon: "JobIconCivilian"
  supervisors: job-supervisors-everyone
  access:
    - Maintenance
  special:
    - !type:AddImplantSpecial
      implants: [JobNetworkImplant]

- type: startingGear
  id: CivilianGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  storage:
    back:
      - BookThresholdHandbook

- type: chameleonOutfit
  id: CivilianChameleonOutfit
  job: Civilian
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: ClothingHandsGlovesColorYellowBudget
