- type: job
  id: Passenger
  name: job-name-civilian
  description: job-description-civilian
  playTimeTracker: JobCivilian
  startingGear: PassengerGear
  icon: "JobIconCivilian"
  supervisors: job-supervisors-everyone
  special:
    - !type:AddImplantSpecial
      implants: [JobNetworkImplant]

- type: startingGear
  id: PassengerGear
  equipment:
    id: CivilianPDA
    ears: ClothingHeadsetGrey
  storage:
    back:
      - BookThresholdHandbook

- type: chameleonOutfit
  id: PassengerChameleonOutfit
  job: Passenger
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: ClothingHandsGlovesColorYellowBudget
