name: Validate

on:
  push:
    branches:
    - upstream-weather-qol
    - service-machines-port
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Debug --no-restore
